credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$ZI2xZf5nyMKwQq54iBV20uozJmSyv7pHRf1Ui7qeySqUCoubElI.y 
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$uQOOZ4KsvlbvQbgDecvHWOdCr.xZUmnlgKYVB5uZvqZcuqraGqLXG
    '7997209':
      email: catocarling@gmail.com
      name: cato carling
      password: $2b$12$BZ7qi.tj2iOJEuiHhkm4TejxfzLdmue0AC4dD6mCCYzhaK1Sca5Sy
    G_man:
      email:
      name: Gautier Gail
      password: $2b$12$32y9j7bFEWyT0rY.CItyIe3m.TmjzVTZIoY/RMvvoqahzq1AXu5SW
    


cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
